import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Captain, Navigation } from '@/components';
import { MAIN_HEIGHT, MAIN_WIDTH } from '@/const/layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`h-screen w-screen flex flex-wrap bg-gray ${inter.className}`}>
				<Captain />
				<Navigation />
				<main className="p-5 bg-gray" style={{ height: MAIN_HEIGHT, width: MAIN_WIDTH }}>
					{children}
				</main>
			</body>
		</html>
	);
}
